version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run: python -m venv venv
      - run: source venv/bin/activate
      - run: pip install -r requirements.txt
      - run: python -m pytest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
